### ISSUE TITLE
Tutorials?

### ISSUE THREAD

**Issue by drvinceknight** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#10]
Loving the languages and editors pages guys. I thought that it could be nice to perhaps put them under a more general 'Tutorials' section and then a collection of 'How to's' could start building up (including disqus comments also).

This could range from hello worlds in various languages to things like using git, gource, maybe @Huaraz2 could write about hacking atom etc...?

Just a though and will leave this with everyone to figure out if they like the idea.

Also, I've added a projects page and just thrown that at the of the menu root but feel free to move it around (that and stuff like tutorials could live under inspiration).

**Comment by Huaraz2** [comment]
Is this issue done with pull request #38?

**Comment by alcarney** [comment]
Possibly - is this now better placed on the Get involved page as an always open 'issue' since there will always be new tutorials to write?

**Comment by drvinceknight** [comment]
I think we can close this issue. Re open if I'm mistaken.
