### ISSUE TITLE
Wording of workshops page

### ISSUE THREAD

**Issue by Huaraz2** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#130]
As you can see in the pic below, the wording above the workshops is wrong, I will change this just not sure what to make it as I am not very good with grammer. @drvinceknight what do you think it should be?

![image](https://cloud.githubusercontent.com/assets/8998661/12989235/76a37d40-d0fc-11e5-930e-226002154939.png)

**Comment by drvinceknight** [comment]
What wording is wrong?

**Comment by Huaraz2** [comment]
It says here are the upcoming workshops but it shows all of them. I know we only have two butt it is confusing as one was last week.

**Comment by drvinceknight** [comment]
Ah yeah! Don't worry too much about the grammar, try your best and it can
always be fixed in the pr. :) :shipit:
