### ISSUE TITLE
Depreciate Gists?

### ISSUE THREAD

**Issue by alcarney** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#139]
Do we want to remove support for gists on the site? Or at least push for code to be put into the backtick syntax like here on github.

- It would help make the site look more consistent and people have more control over how their themes look
- It might reduce compexity? By keeping code and content all in one place?

**Comment by Huaraz2** [comment]
I like this idea, can't read the code in some of the gists with certain themes.

**Comment by drvinceknight** [comment]
I'm for this :+1:

**Comment by Huaraz2** [comment]
I can do this tomorrow
