### ISSUE TITLE
Unable to read words on landing page with new themes

### ISSUE THREAD

**Issue by Huaraz2** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#143]
The landing page with `Geriant's theme`:
![image](https://cloud.githubusercontent.com/assets/8998661/13036027/82d5c94c-d354-11e5-8e71-dd557a044b54.png)

The landing page with `Classic Inverted` theme:
![image](https://cloud.githubusercontent.com/assets/8998661/13036038/bf5e867e-d354-11e5-9add-30aa494739d9.png)

Landing page with `Matrix` theme:
![image](https://cloud.githubusercontent.com/assets/8998661/13036041/efe8ff18-d354-11e5-97cf-becba9b4d51c.png)

As you can see in the above pics, the writing on the landing page is either very difficult or impossible to read. Any ideas as to how we fix this @alcarney? Could we possibly make the `$background-color` variable come up behind the words (in all the themes apart from `Geriant's Theme` it would then be readable).

**Comment by alcarney** [comment]
Yup themes need updating to make the landing page readable.

Basically there are two new classes that rules need to be created for

- `landing`: This will affect pretty much the entire page
- `reason`: This will affect each of the "Code club is..." statements 

However try importing `_sass/_main/_landiningpage` to each theme that might fix some of them....

**Comment by Huaraz2** [comment]
@alcarney Ok will have a look at this in a bit currently doing game theory homework 1

**Comment by alcarney** [comment]
I'm going to try and create a `_styles` folder that people can grab bits from to style the site using only variables in their main theme file, once in place it should minimise breaking changes on the website
