### ISSUE TITLE
Blog post for first editor off

### ISSUE THREAD

**Issue by drvinceknight** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#17]
Hi guys, I've started a blog post about the editor off: https://github.com/CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io/blob/editor-off-1/_drafts/the-first-editor-off.md

@Huaraz2, @alcarney and @sluenenglish add a quick description of what you did :+1: 

Keep it in `_drafts` and on the `editor-off-1` branch for now.

**Comment by sluenenglish** [comment]
I've added my bit :+1:

**Comment by drvinceknight** [comment]
> Vince added that a good use of this function could be reading the output of an ls command into a .gitignore file.

I meant the output of `git status` which would/could automatically spit out files you don't want or haven't added yet, it would also go through the directory tree.

**Comment by sluenenglish** [comment]
I just changed that sentence, let me know if it's still not right

**Comment by drvinceknight** [comment]
:+1:
