### ISSUE TITLE
Roadmap for new contributors

### ISSUE THREAD

**Issue by alcarney** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#19]
I think it would be good if we compiled a quick reference for potential new contributors telling them where they can find certain elements of the site that they may wish to change e.g.

- How to add items to the menus
- How the site structured (what's included by default in headers etc.)
- Clearly marking stuff that never should be touched (like the section in _includes/head.html which adds the google analytics tracker etc.)

Also should this be made part of the site itself or here on github - either in the README or the wiki?

Let me know your thoughts :)

**Comment by drvinceknight** [comment]
README or wiki sounds great.

This should be coupled by sitting down and walking people through it. Perhaps next week we could do that? Have someone on the monitor showing people what to do?
