### ISSUE TITLE
Blog post for second editor off

### ISSUE THREAD

**Issue by drvinceknight** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#20]

**Comment by alcarney** [comment]
Draft post can be found [here](https://github.com/CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io/blob/editor-off-2/_drafts/editor-off-2.md)

**Comment by drvinceknight** [comment]
I have written my post and so has @Huaraz2

**Comment by Huaraz2** [comment]
@hhlorrimore you still need to do your bit
