### ISSUE TITLE
Can only get to documentation when I add /docs/ to the link

### ISSUE THREAD

**Issue by Huaraz2** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#209]
We need to add a link to the sites documentation somewhere on the site, maybe in the get involved page?

**Comment by alcarney** [comment]
You can get to the documentation via the code club's website project page

**Comment by Huaraz2** [comment]
@alcarney That's cool but I think we need a link somewhere else as well as that is not very obvious

**Comment by alcarney** [comment]
Well I think adding one to the README would be a good idea.

**Comment by Huaraz2** [comment]
@alcarney Very true

**Comment by alcarney** [comment]
People only really need to get to the documentation if they are going to contribute to the site which means they'll be directed to the README anyway. 

Perhaps we could make the project pages more obvious... But they are all accessible straight from the getting involved page

**Comment by Huaraz2** [comment]
@alcarney Fair enough alex
