### ISSUE TITLE
Travis?

### ISSUE THREAD

**Issue by alcarney** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#21]
Is it worth us integrating travis to this repository? It looks like it's possible [see here](http://jekyllrb.com/docs/continuous-integration/) 

I know we don't have many tests.... yet ;) But it might act as incentive gradually adding more tests increasing coverage and seeing all our builds pass and then we can be sure that any new additions aren't going to bring any surprises....

Or is not worth it??

**Comment by drvinceknight** [comment]
Definitely worth it.

Love the idea.

**Comment by drvinceknight** [comment]
:+1: :shipit:
