### ISSUE TITLE
Colenel Sarge broke the website

### ISSUE THREAD

**Issue by Huaraz2** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#23]
![website is broken](https://cloud.githubusercontent.com/assets/8998661/10672382/a8542f28-78e7-11e5-995f-ab6a675da515.png)

I SUMMON THE CODE JANITOR

**Comment by alcarney** [comment]
Turn my back for 5 minutes.... ;)

**Comment by drvinceknight** [comment]
:+1: :smile: :muscle: :shipit: :shipit: :shipit:

**Comment by drvinceknight** [comment]
> I SUMMON THE CODE JANITOR

:bow: :bow: :bow: :shipit:

**Comment by Huaraz2** [comment]
@drvinceknight you have well and truly BROKE THE WEBSITE, @timothyf1 fixed it but it will not update
![how](https://cloud.githubusercontent.com/assets/8998661/10761485/8807e84c-7cb9-11e5-96fd-8cac38f4c9d2.png)

**Comment by Huaraz2** [comment]
fixed in all the commits today

**Comment by Huaraz2** [comment]
4ad79ce1512a63cec75f75b4a2753a8a30925c3e
78008fd9c7f03d471c53bc7e18c44018a723a719
437b8239e1d5926093da8ecf1bc9a2df146ff997
0a3f26495c565917eb9fea031560196d6d2f921c
ca02cd7ee8a97b005f066cbb65448b88d6a6f165
8527206d1bc8b3eaf7a8ddc6effdb104499f3ee4
c1a85391a2049da31ebf34e8870af53b5b89e613
5930653ac9f6b99526cfdcb4157c751371c4ebf7

**Comment by drvinceknight** [comment]
:+1: :shipit:
