### ISSUE TITLE
Implement micro workshops

### ISSUE THREAD

**Issue by drvinceknight** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#72]
This is following the discussion we had. I will take this one.

It needs two things:

1. Implement a website section about microworkshops (to announce upcoming ones and possibly a spot for links etc of resources).
2. Come up with a beginning schedule of microworkshops

I'll take this one.

**Comment by alcarney** [comment]
So are there any plans for a wrokshop this week?

**Comment by drvinceknight** [comment]
> So are there any plans for a wrokshop this week?

Django? I can do it, although if someone else wanted to I'd prefer that.

**Comment by geraintpalmer** [comment]
I'm not here this week. But I don't mind doing a basic git/GitHub one at some point

**Comment by drvinceknight** [comment]
Sounds great Geraint, perhaps the week after although it might be worth
doing kivy after Django so perhaps the week after that...

**Comment by alcarney** [comment]
Closing, since the wrokshop system is now in place
