### ISSUE TITLE
Get travis to build the website

### ISSUE THREAD

**Issue by alcarney** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#80]
Currently when we push changes onto `master` Github then builds the website using it's own Jekyll environment and a small collection of supported gems. They also do not let users execute their own code during this process - rightly so!

However this can be a bit restrictive, for example we recently enabled Jekyll's built in pagination feature to allow us to split up posts on the blog into many pages once we get above a certain threshold. Unfortanely this cannot be done for the category pages using stock Jekyll and requires we write some ruby code to handle this - which is unsupported by Github's build environment.

I have seen a few guides out there which use Travis to automatically build and deploy to Github when changes are made so it should be possible. 

Just wondering what people's thoughts are?

**Comment by drvinceknight** [comment]
> Just wondering what people's thoughts are?

This is certainly a possibility.

My suggestion would be to keep things simple (ie not move the building of the site to travis). I'm not sure if there is much to be gained by doing this (sure the pagination would be nice but...).

It's not overly complicated to do but just foreseeing a time when something breaks (not that this is likely) and people don't have expertise or time to fix. 

My vote would be to keep a basic low hanging standard. Just thinking of reducing the number of moving parts.
