### ISSUE TITLE
Include something in README about running tests...

### ISSUE THREAD

**Issue by drvinceknight** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#81]

**Comment by alcarney** [comment]
There is a mention about running the tests under the Contributing section of the README. Where we say please run the tests before submitting a PR and it gives the command to do so (although it needs to be updated).

Should it be more obvious with neon lights and brass bands though? :p

**Comment by drvinceknight** [comment]
I think having a subsection or some bold text about **running tests** would do no harm. Also perhaps something about how to get `rake` perhaps?

**Comment by alcarney** [comment]
Sure :)

As long as `bundle install` works ok then you will have rake since it's
included as a dependency of the website

**Comment by drvinceknight** [comment]
> As long as `bundle install` works ok then you will have rake since it's
> included as a dependency of the website

I think that should be included in the README (although running that broke all the things for me, ended up uninstalling a bunch of stuff, including bundle, my install problem, not an actual issue).
