### ISSUE TITLE
Unit Testing Links?

### ISSUE THREAD

**Issue by alcarney** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#9]
Having just finished writing the initial draft for the C language page, I think I counted 10-12 links and that was being conservative. I'm pretty sure we could easily add another 10 as we start adding more information and linking internally to the other lanaguage pages. Not to mention other pages as they are added to the site.

So is it possible using Selenium or something similar (since Selenium is python only??) to test each link on a page and at least check that it goes to a valid webpage?

**Comment by alcarney** [comment]
Maybe we could use this somehow, we might have to run it locally somewhere https://github.com/bamos/girl

**Comment by drvinceknight** [comment]
Looks neat, I've figured out travis this weekend: might be able to use that (so ridiculously powerful).

**Comment by alcarney** [comment]
Cool I've been wanting to look into Travis for a while now

**Comment by drvinceknight** [comment]
We can play around with it on Friday if you want: so cool.

(It's implemented on my Axelrod repo)
